### ISSUE TITLE
Package not available in package control

### ISSUE THREAD

**Issue by jarias** [sirreal/SublimeLinter-contrib-go#1]
All your other linter are there except this one

**Comment by sirreal** [comment]
I abandoned this linter (and never release it on PC) because `go` didn't seem to have a built-in linter/syntax-checker like to `php -l`.

`govet`, `golint` and `gotype` seemed to be good fits for linters.

Perhaps a `gofmt` linter could/should be written, but I have not plans for writing it at this time.

Unless this has changed and go has something build in, this package doesn't have a future.
